consumer:
    topic: test
    bootstrap_servers: ['localhost:9092']
    group_id: my-group
    auto_offset_reset: earliest
    enable_auto_commit: False
    consumer_timeout_ms: 1000
other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes